# Generated by Django 5.0.7 on 2024-08-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(blank=None, max_length=30)),
                ('description', models.TextField(blank=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('doc_name', models.TextField(max_length=30)),
                ('message', models.TextField(max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.department')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_spe', models.CharField(blank=True, max_length=100)),
                ('doc_image', models.CharField(max_length=500)),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.department')),
            ],
        ),
    ]
